### ISSUE TITLE
TypeError: restart_subtask() got an unexpected keyword argument 'new_state'

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#5158]
## Description

**Golem Version**: 0.23.0

**OS**: Linux

**Mainnet/Testnet**: Mainnet

**Description of the issue**:

When running gWASM task there is an error that appears in logs. I don't know what are the actual consequences.

**Actual result**:

?

## Steps To Reproduce

Run a gWASM task, I guess.

## Expected behavior

It shouldn't throw `TypeError` exceptions.

## Logs and any additional context

```
2020-04-02 15:22:33 CRITICAL twisted                             Unhandled error in Deferred:
2020-04-02 15:22:33 CRITICAL twisted
Traceback (most recent call last):
  File "/data/golem/golem_git/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/data/golem/golem_git/golem/task/tasksession.py", line 744, in _react_to_cannot_compute_task
    timeout,
  File "/data/golem/golem_git/golem/core/common.py", line 189, in func_wrapper
    return func(*args, **kwargs)
  File "/data/golem/golem_git/golem/task/taskmanager.py", line 874, in task_computation_cancelled
    new_status=SubtaskStatus.cancelled,
  File "/data/golem/golem_git/golem/core/common.py", line 189, in func_wrapper
    return func(*args, **kwargs)
  File "/data/golem/golem_git/golem/task/taskmanager.py", line 1034, in restart_subtask
    new_state=new_status,
TypeError: restart_subtask() got an unexpected keyword argument 'new_state'
```

## References

Introduced by #5127
