### PR TITLE
Fix restore_locks

### LINKED ISSUE #3581: AttributeError: 'SubtaskState' object has no attribute 'status'
introduced in #3494

https://github.com/golemfactory/golem/blob/e422d056972e312c92467848247e4fa92fefdb7a/golem/client.py#L483

AttributeError: 'SubtaskState' object has no attribute 'status'

Because 'SubtaskState' object has attribute 'subtask_status'

### PR DESCRIPTION
**Pull request by Krigpl**
Fixes #3581

### CODE REVIEW

**Review by etam — APPROVED** [review]
ok
