### ISSUE TITLE
AttributeError: 'SubtaskState' object has no attribute 'status'

### ISSUE THREAD

**Issue by etam** [golemfactory/clay#3581]
introduced in #3494

https://github.com/golemfactory/golem/blob/e422d056972e312c92467848247e4fa92fefdb7a/golem/client.py#L483

AttributeError: 'SubtaskState' object has no attribute 'status'

Because 'SubtaskState' object has attribute 'subtask_status'

**Comment by etam** [comment]
If you add a type annotation to `TaskState.subtask_states` would `mypy` catch this?
